// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_s65k0awPjvLBwMbZGf5QWE7SpJTOydE',
    appId: '1:127146027123:web:9c4676736e5ca12d6f6206',
    messagingSenderId: '127146027123',
    projectId: 'zanbeelapp-8cd30',
    authDomain: 'zanbeelapp-8cd30.firebaseapp.com',
    storageBucket: 'zanbeelapp-8cd30.firebasestorage.app',
    measurementId: 'G-YSN2RNBD40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxulxOaFYXY_rkCNcH0oh-LpUJsv663k',
    appId: '1:127146027123:android:501314bb9feeaebd6f6206',
    messagingSenderId: '127146027123',
    projectId: 'zanbeelapp-8cd30',
    storageBucket: 'zanbeelapp-8cd30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlHKF6E0X4Cde4bEBe09QSIqu3Y4jyl1I',
    appId: '1:127146027123:ios:a11217bf57014fcc6f6206',
    messagingSenderId: '127146027123',
    projectId: 'zanbeelapp-8cd30',
    storageBucket: 'zanbeelapp-8cd30.firebasestorage.app',
    iosBundleId: 'com.zambeel.store.zambeelStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlHKF6E0X4Cde4bEBe09QSIqu3Y4jyl1I',
    appId: '1:127146027123:ios:a11217bf57014fcc6f6206',
    messagingSenderId: '127146027123',
    projectId: 'zanbeelapp-8cd30',
    storageBucket: 'zanbeelapp-8cd30.firebasestorage.app',
    iosBundleId: 'com.zambeel.store.zambeelStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_s65k0awPjvLBwMbZGf5QWE7SpJTOydE',
    appId: '1:127146027123:web:fd46054d279caa516f6206',
    messagingSenderId: '127146027123',
    projectId: 'zanbeelapp-8cd30',
    authDomain: 'zanbeelapp-8cd30.firebaseapp.com',
    storageBucket: 'zanbeelapp-8cd30.firebasestorage.app',
    measurementId: 'G-8RE8X37J8R',
  );
}
